---
# Source: prometheus-adapter/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-prometheus-adapter
  namespace: elastic-stack-logging
  labels:    
    helm.sh/chart: prometheus-adapter-4.9.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-adapter
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/instance: adapter
    app.kubernetes.io/version: "v0.11.2"
data:
  config.yaml: |
    rules:
    - seriesQuery: 'nginx_ingress_controller_nginx_process_requests_total{kubernetes_namespace!="", controller_pod!=""}'
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          controller_pod: {resource: "pod"}
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'