---
# Source: prometheus-adapter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:    
    helm.sh/chart: prometheus-adapter-4.9.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-adapter
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/instance: adapter
    app.kubernetes.io/version: "v0.11.2"
  name: adapter-prometheus-adapter
  namespace: elastic-stack-logging
spec:
  replicas: 1
  strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:      
      app.kubernetes.io/name: prometheus-adapter
      app.kubernetes.io/instance: adapter
  template:
    metadata:
      labels:        
        helm.sh/chart: prometheus-adapter-4.9.0
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: metrics
        app.kubernetes.io/part-of: prometheus-adapter
        app.kubernetes.io/name: prometheus-adapter
        app.kubernetes.io/instance: adapter
        app.kubernetes.io/version: "v0.11.2"
      name: prometheus-adapter
      annotations:
        checksum/config: e50d787f87c549cd6de4da4b7afbb7fc1a8d60334e33c8dbb2b92d4ad2a39d09
    spec:
      serviceAccountName: adapter-prometheus-adapter
      containers:
      - name: prometheus-adapter
        image: "registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.11.2"
        imagePullPolicy: IfNotPresent
        args:
        - /adapter
        - --secure-port=6443
        - --cert-dir=/tmp/cert
        - --prometheus-url=http://prometheus:9090
        - --metrics-relist-interval=1m
        - --v=4
        - --config=/etc/adapter/config.yaml
        ports:
        - containerPort: 6443
          name: https
        livenessProbe:
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          initialDelaySeconds: 30
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /etc/adapter/
          name: config
          readOnly: true
        - mountPath: /tmp
          name: tmp
      nodeSelector:
        {}
      affinity:
        {}
      topologySpreadConstraints:
        []
      securityContext:
        fsGroup: 10001
      tolerations:
        []
      volumes:
      - name: config
        configMap:
          name: adapter-prometheus-adapter
      - name: tmp
        emptyDir: {}
