---
# Source: prometheus-adapter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:    
    helm.sh/chart: prometheus-adapter-4.9.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-adapter
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/instance: adapter
    app.kubernetes.io/version: "v0.11.2"
  name: adapter-prometheus-adapter
  namespace: elastic-stack-logging
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: https
  selector:    
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/instance: adapter
  type: ClusterIP
