kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: kube-system

resources:
- github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.3

patchesStrategicMerge:
  - |-
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: efs-csi-controller
    spec:
      template:
        spec:
          containers:
          - name: efs-plugin
            args:
              - --endpoint=$(CSI_ENDPOINT)
              - --logtostderr
              - --v=2
              - --delete-access-point-root-dir=true
              - --vol-metrics-opt-in=false
