kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- ../../../../../base/logging/elastic-stack/logstash

patchesStrategicMerge:
- logstash-limits.yaml
- hpa-limits.yaml