apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: elastic-stack-logging
spec:
  general:
    serviceName: opensearch-cluster
    version: 2.8.0
    image: public.ecr.aws/r2h3l6e4/pingcloud-monitoring/opensearch/dev:v1.19-release-branch-latest
    additionalConfig:
      node.search.cache.size: 128mb
  confMgmt:
    smartScaler: true
  security:
    config:
#      adminCredentialsSecret:
#        # For operator auth to the OS cluster
#        name: os-connections-creds
      securityConfigSecret:
       ##Pre create this secret with required security configs, to override the default settings
       name: opensearch-securityconfig
    tls:
      transport:
        generate: true
      http:
        generate: true
  dashboards:
    enable: true
    version: 2.8.0
    replicas: 1
#    opensearchCredentialsSecret:
#      name: osd-credentials
    image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/opensearchproject/opensearch-dashboards:2.8.0
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: hot
      replicas: 3
      diskSize: "10Gi"
      nodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      env:
        - name: node.attr.temp
          value: hot
      roles:
        - "cluster_manager"
        - "data"
        - "ingest"
        - "remote_cluster_client"
        - "search"
      persistence:
        pvc:
          storageClass: opensearch-gp3
          accessModes:
          - "ReadWriteOnce"
    - component: warm
      replicas: 3
      diskSize: "10Gi"
      nodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      env:
        - name: node.attr.temp
          value: warm
      roles:
        - "data"
        - "remote_cluster_client"
      persistence:
        pvc:
          storageClass: opensearch-gp3
          accessModes:
          - "ReadWriteOnce"
#---
#apiVersion: opensearch.opster.io/v1
#kind: OpensearchComponentTemplate
#metadata:
#  namespace: elastic-stack-logging
#  name: backup-jobs
#spec:
#  opensearchCluster:
#    name: opensearch-cluster
#  template: # required
#    aliases: # optional
#      my_alias: {}
#    settings: # optional
#      number_of_shards: 1
#      number_of_replicas: 1
#      refresh_interval: 30s
#    mappings:
#      properties:
#        "@timestamp":
#          type: date
#        "@version":
#          type: text
#          fields:
#            keyword:
#              type: keyword
#              ignore_above: 256
#        cluster_name:
#          type: text
#          fields:
#            keyword:
#              type: keyword
#              ignore_above: 256
#        host:
#          type: text
#          fields:
#            keyword:
#              type: keyword
#              ignore_above: 256
#        kubernetes:
#          properties:
#            container_hash:
#              type: text
#              fields:
#                keyword:
#                  type: keyword
#                  ignore_above: 256
#            container_image:
#              type: text
#              fields:
#                keyword:
#                  type: keyword
#                  ignore_above: 256
#            container_name:
#              type: text
#              fields:
#                keyword:
#                  type: keyword
#                  ignore_above: 256
#            docker_id:
#              type: text
#              fields:
#                keyword:
#                  type: keyword
#                  ignore_above: 256
#            host:
#              type: text
#              fields:
#                keyword:
#                  type: keyword
#                  ignore_above: 256
#            labels:
#              properties:
#                app:
#                  type: text
#                  fields:
#                    keyword:
#                      type: keyword
#                      ignore_above: 256
#                controller-uid:
#                  type: text
#                  fields:
#                    keyword:
#                      type: keyword
#                      ignore_above: 256
#                job-name:
#                  type: text
#                  fields:
#                    keyword:
#                      type: keyword
#                      ignore_above: 256
#            namespace_name:
#              type: text
#              fields:
#                keyword:
#                  type: keyword
#                  ignore_above: 256
#            pod_id:
#              type: text
#              fields:
#                keyword:
#                  type: keyword
#                  ignore_above: 256
#            pod_name:
#              type: text
#              fields:
#                keyword:
#                  type: keyword
#                  ignore_above: 256
#        message:
#          type: text
#        stream:
#          type: text
#          fields:
#            keyword:
#              type: keyword
#              ignore_above: 256
#  version: 1 # optional
#  allowAutoCreate: true # optional
#  _meta: # optional
#    description: example description
#---
#apiVersion: opensearch.opster.io/v1
#kind: OpensearchIndexTemplate
#metadata:
#  namespace: elastic-stack-logging
#  name: backup-jobs
#spec:
#  opensearchCluster:
#    name: opensearch-cluster
#  indexPatterns: # required index patterns
#    - "backup-jobs-*"
#  priority: 100 # optional
#  composedOf:
#    - backup-jobs
#  template: {} # optional
#  version: 1 # optional
#  _meta: {} # optional

#---
#apiVersion: opensearch.opster.io/v1
#kind: OpensearchUser
#metadata:
#  name: sample-os-user
#  namespace: elastic-stack-logging
#spec:
#  opensearchCluster:
#    name: opensearch-cluster
#  passwordFrom:
#    name: sample-user-password
#    key: password
#  backendRoles:
#  - kibanauser