kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- cluster.yaml
#- configs
- security_configs
#- pdb.yaml
#- rbac.yaml
#- service.yaml
#- sts.yaml
- index-templates
- storageclass.yaml
#- certs.yaml
- ism-policies
- alerts
- notifications
- bootstrap.yaml
#- secret.yaml
