apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: elastic-stack-logging
spec:
  general:
    serviceName: opensearch-cluster
    version: 2.8.0
    image: public.ecr.aws/r2h3l6e4/pingcloud-monitoring/opensearch/dev:v1.19-release-branch-latest
    additionalConfig:
      node.search.cache.size: 128mb
  confMgmt:
    smartScaler: true
  security:
    config:
#      adminCredentialsSecret:
#        # For operator auth to the OS cluster
#        name: os-connections-creds
      securityConfigSecret:
       ##Pre create this secret with required security configs, to override the default settings
       name: opensearch-securityconfig
    tls:
      transport:
        generate: true
      http:
        generate: true
  dashboards:
    enable: true
    version: 2.8.0
    replicas: 1
#    opensearchCredentialsSecret:
#      name: sample-user-password
    image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/opensearchproject/opensearch-dashboards:2.8.0
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: hot
      replicas: 3
      diskSize: "10Gi"
      nodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      env:
        - name: node.attr.temp
          value: hot
      roles:
        - "cluster_manager"
        - "data"
        - "ingest"
        - "remote_cluster_client"
        - "search"
      persistence:
        pvc:
          storageClass: opensearch-gp3
          accessModes:
          - "ReadWriteOnce"
    - component: warm
      replicas: 3
      diskSize: "10Gi"
      nodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      env:
        - name: node.attr.temp
          value: warm
      roles:
        - "data"
        - "remote_cluster_client"
      persistence:
        pvc:
          storageClass: opensearch-gp3
          accessModes:
          - "ReadWriteOnce"
