_meta:
  type: "config"
  config_version: "2"
config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authz:
      test:
        description: "Authorize"
        http_enabled: true
        transport_enabled: true
        authorization_backend:
          type: noop
    authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: "0"
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: email
            roles_key: groups
            openid_connect_url: https://auth.pingone.eu/277c89a6-fb5d-477d-b367-2422f473dc9b/as/.well-known/openid-configuration
        authentication_backend:
          type: noop