apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
- crds.yaml

# Patch the CRDs such that argocd will sync them properly
patchesJson6902:
  - target:
      version: v1
      kind: CustomResourceDefinition
      name: grafanas.grafana.integreatly.org
      namespace: prometheus
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "Replace=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: grafanadashboards.grafana.integreatly.org
      namespace: prometheus
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "Replace=true"  

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: grafanadatasources.grafana.integreatly.org
      namespace: prometheus
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "Replace=true"  

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: grafanafolders.grafana.integreatly.org
      namespace: prometheus
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "Replace=true"