apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-elastic
spec:
  template:
    spec:
      containers:
        - name: logstash
          resources:
            limits:
              cpu: "1.5"
              memory: 3Gi
            requests:
              cpu: 300m
              memory: 2Gi
          env:
            - name: LS_JAVA_OPTS
              value: '-Xms3g -Xmx3g'
            - name: PIPELINE_WORKERS
              value: "2"
            - name: QUEUE_MAX_BYTES
              value: 1500gb