apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-operator-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          # This is a dev image used to remove unneeded check for grafana folder permissions
          # Waiting for this PR https://github.com/grafana-operator/grafana-operator/pull/1129
          image: public.ecr.aws/r2h3l6e4/dev/grafana-operator:dev
