## This is a Prometheus alerting rules for the logging
---

groups:
- name: elastic-stack-logging
  rules:
  - alert: FluentBit dropping records
    expr: sum(increase(fluentbit_output_dropped_records_total[1m])) by (name) > 10
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: FluentBit dropping records for output {{ $labels.name }}
      description: "A FluentBit outputs dropping records. Possible {{ $labels.name }} output is down.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: FluentBit retries failed
    expr: sum(increase(fluentbit_output_retries_total[1m])) by (name) > 50
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: FluentBit has many retries in the output {{ $labels.name }}
      description: "A FluentBit has many retries in the output. Possible {{ $labels.name }} output is down.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: Logstash pipeline is growing
    expr: sum(increase(logstash_node_queue_events[1m])) by (instance, pipeline) > 100000
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: Logstash pipeline {{ $labels.pipeline }} is growing on {{ $labels.instance }}
      description: "A Logstash pipeline is growing. Possible {{ $labels.pipeline }} is overloaded or logs spike.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: Logstash has no outgoing events
    expr: sum(increase(logstash_node_pipeline_events_out_total{pipeline!="alerts"}[1m])) by (instance, pipeline) == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: Logstash pipeline {{ $labels.pipeline }} didn't produce any outgoing events on {{ $labels.instance }}
      description: "An outgoing Logstash pipeline {{ $labels.pipeline }} is dead. Possible no outgoing events.\nCheck logs destination availability.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: Logstash has no incoming events
    expr: sum(increase(logstash_node_pipeline_events_in_total{pipeline!="alerts"}[1m])) by (instance, pipeline) == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: Logstash pipeline {{ $labels.pipeline }} didn't recieve any incoming events on {{ $labels.instance }}
      description: "An incoming Logstash pipeline {{ $labels.pipeline }} is dead. Possible some inputs stuck.\nCheck fluent-bit logs.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: FluentBit dramatically changed input <> output
    expr: ((sum(fluentbit_input_records_total{name=~"tail.*|systemd.*"}) by (instance)) - (sum(fluentbit_output_proc_records_total) by (instance)))/sum(fluentbit_input_records_total{name=~"tail.*|systemd.*"}) by (instance)*100 > 10
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: FluentBit log flow dramatically changed on {{ $labels.instance }}
      description: "The difference between inputs and outputs on {{ $labels.instance }} been dramatically changed.\nPossible some inputs stuck or logs spike.\nCheck fluent-bit logs.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
