apiVersion: v1
kind: Secret
metadata:
  name: os-logstash-creds
  namespace: elastic-stack-logging
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/patch: "true"
    argocd.argoproj.io/sync-options: Prune=false
data:
  username: bG9nc3Rhc2g=
  password: Y3lTVEhHaUNmbTlObkdkMmNKRTFBbW9HdQ==
